const $=id=>document.getElementById(id);
const slider=$("infillSlider"),number=$("infillNumber");
const patterns=document.querySelectorAll(".pattern");
const stlInput=$("stlInput"),projectInput=$("projectInput"),openStlButton=$("openStlButton"),viewport=$("viewport"),dropOverlay=$("dropOverlay"),printerSelect=$("printerSelect");
const materialBrowser=$("materialBrowser"),materialName=$("materialName"),materialDescription=$("materialDescription"),materialSpecs=$("materialSpecs");
const saveProjectButton=$("saveProjectButton"),openProjectButton=$("openProjectButton"),layerHeightSelect=$("layerHeightSelect");
const objectList=$("objectList"),printerSummary=$("printerSummary");
const transformButtons={translate:$("moveButton"),rotate:$("rotateButton"),scale:$("scaleButton")};
let selectedMaterial=null,selectedPattern="Grid",loadedModelName=null,printerProfiles=[],materialFamilies=[];

slider?.addEventListener("input",()=>number.textContent=slider.value);
patterns.forEach(p=>p.addEventListener("click",()=>{patterns.forEach(x=>x.classList.remove("selected"));p.classList.add("selected");selectedPattern=p.dataset.pattern||p.textContent.trim();}));
Object.entries(transformButtons).forEach(([mode,b])=>b?.addEventListener("click",()=>{Object.values(transformButtons).forEach(x=>x?.classList.remove("active"));b.classList.add("active");window.csliceViewer?.setTransformMode(mode);}));

openStlButton?.addEventListener("click",()=>{stlInput.value="";stlInput.click();});
$("addObjectButton")?.addEventListener("click",()=>{stlInput.value="";stlInput.click();});
stlInput?.addEventListener("change",async e=>{const files=Array.from(e.target.files||[]);for(const f of files)await loadFile(f);e.target.value="";});

["dragenter","dragover"].forEach(n=>viewport?.addEventListener(n,e=>{e.preventDefault();dropOverlay?.classList.remove("hidden");dropOverlay?.classList.add("active");}));
["dragleave","drop"].forEach(n=>viewport?.addEventListener(n,e=>{e.preventDefault();dropOverlay?.classList.remove("active");}));
viewport?.addEventListener("drop",e=>{const files=Array.from(e.dataTransfer?.files||[]);files.filter(isSTL).forEach(loadFile);if(files.length&&!files.some(isSTL))setStatus("Please choose an STL file");});
function isSTL(file){return file&&(/\.stl$/i.test(file.name)||["model/stl","application/sla","application/octet-stream"].includes(file.type));}
async function loadFile(file,savedState=null){if(!isSTL(file)){setStatus("That file is not an STL");return;}try{setStatus(`Loading ${file.name}…`);const buffer=await file.arrayBuffer();loadedModelName=file.name;const id=window.csliceViewer?.loadSTL(buffer,file.name,savedState);if(id) setStatus(`${file.name} loaded`);}catch(e){console.error(e);setStatus("Could not read that STL file");}}
function setStatus(t){const el=$("viewerStatus");if(el)el.textContent=t;}
$("fitButton")?.addEventListener("click",()=>window.csliceViewer?.fitModel());$("resetViewButton")?.addEventListener("click",()=>window.csliceViewer?.resetView());$("deleteObjectButton")?.addEventListener("click",()=>window.csliceViewer?.removeObject());$("duplicateObjectButton")?.addEventListener("click",()=>window.csliceViewer?.duplicateObject());
printerSelect?.addEventListener("change",()=>{localStorage.setItem("cslice-printer",printerSelect.value);applyPrinter(printerProfiles.find(p=>p.id===printerSelect.value));});
async function applyPrinter(p){if(!p)return;const v=p.buildVolume;if(v)window.csliceViewer?.setBuildPlate(v.x,v.y,v.z);if(printerSummary)printerSummary.innerHTML=`<b>${v.x} × ${v.y} × ${v.z} mm</b><span>${p.manufacturer} • ${p.defaultNozzle||.4} mm nozzle</span>`;updateMaterialAvailability(p);setStatus(`${p.name} — ${v.x} × ${v.y} × ${v.z} mm build volume`);}
async function loadPrinterLibrary(){try{const r=await fetch("data/printers/index.json",{cache:"no-store"});if(!r.ok)throw Error();const index=await r.json();printerProfiles=await Promise.all(index.printers.map(async file=>{const r=await fetch(`data/printers/${file}`,{cache:"no-store"});if(!r.ok)throw Error(file);const p=await r.json();return {...p,id:p.id||file.replace(/\.json$/i,"")};}));printerSelect.innerHTML="";printerProfiles.forEach(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=p.name;printerSelect.appendChild(o);});const saved=localStorage.getItem("cslice-printer");if(saved&&printerProfiles.some(p=>p.id===saved))printerSelect.value=saved;await applyPrinter(printerProfiles.find(p=>p.id===printerSelect.value));}catch(e){console.error(e);printerSelect.innerHTML='<option value="k2-plus">Creality K2 Plus</option>';}}
const viewerSync=setInterval(()=>{if(window.csliceViewer&&printerProfiles.length){applyPrinter(printerProfiles.find(p=>p.id===printerSelect.value));clearInterval(viewerSync)}},50);
async function loadMaterialLibrary(){try{const r=await fetch("data/materials/index.json",{cache:"no-store"});const index=await r.json();materialFamilies=await Promise.all(index.families.map(async file=>(await fetch(`data/materials/${file}`,{cache:"no-store"})).json()));renderMaterialLibrary();}catch(e){console.error(e);if(materialBrowser)materialBrowser.innerHTML='<div class="material-loading">Material library unavailable</div>';}}
function renderMaterialLibrary(){if(!materialBrowser)return;materialBrowser.innerHTML="";const p=printerProfiles.find(x=>x.id===printerSelect.value);materialFamilies.forEach((family,fi)=>{const d=document.createElement("details");d.className="material-family";if(fi===0)d.open=true;const s=document.createElement("summary");s.textContent=family.family;d.appendChild(s);const vbox=document.createElement("div");vbox.className="material-variants";family.variants.forEach((v,vi)=>{const b=document.createElement("button");b.className="material-variant";b.textContent=v.name;const supported=!p?.supportedMaterials||p.supportedMaterials.some(n=>n.toLowerCase()===v.name.toLowerCase());if(!supported){b.classList.add("unsupported");b.title=`${v.name} is not listed as supported by ${p.name}`;}b.onclick=()=>selectMaterial(v,family,b);vbox.appendChild(b);if(fi===0&&vi===0&&!selectedMaterial)selectMaterial(v,family,b);});d.appendChild(vbox);materialBrowser.appendChild(d);});}
function updateMaterialAvailability(p){if(!materialFamilies.length)return;renderMaterialLibrary();if(selectedMaterial&&!p.supportedMaterials?.some(n=>n.toLowerCase()===selectedMaterial.name.toLowerCase()))setStatus(`${p.name} — selected material may not be supported`);}
function selectMaterial(v,f,b){selectedMaterial={...v,family:f.family};document.querySelectorAll(".material-variant").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");if(materialName)materialName.textContent=`${f.family} — ${v.name}`;if(materialDescription)materialDescription.textContent=v.description;if(materialSpecs)materialSpecs.innerHTML=`<div class="material-spec"><b>Nozzle</b>${range(v.recommendedNozzle)}°C</div><div class="material-spec"><b>Bed</b>${range(v.recommendedBed)}°C</div><div class="material-spec"><b>Fan</b>${range(v.fan)}%</div><div class="material-spec"><b>Speed</b>${range(v.speed)} mm/s</div>`;}
function range(v){return Array.isArray(v)?(v.length===2?`${v[0]}–${v[1]}`:v.join(" / ")):v;}
function syncObjectList(){const list=window.csliceViewer?.getObjects?.()||[],sel=window.csliceViewer?.getSelectedId?.();if(!objectList)return;objectList.innerHTML="";if(!list.length){objectList.innerHTML='<div class="empty-objects">No objects loaded</div>';return;}list.forEach(o=>{const b=document.createElement("button");b.className=`object-item ${o.id===sel?"selected":""}`;b.innerHTML=`<span class="object-icon">◇</span><span class="object-name">${escapeHtml(o.name)}</span><span class="object-state ${o.fits?"ok":"bad"}">${o.fits?"✓":"!"}</span>`;b.onclick=()=>window.csliceViewer?.selectObject(o.id);objectList.appendChild(b);});}
window.csliceApp={syncObjectList};function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function currentProject(){return{format:"CSlice Project",version:3,createdAt:new Date().toISOString(),printer:printerSelect.value,filament:selectedMaterial?.name||null,layerHeight:Number(layerHeightSelect.value),infill:{density:Number(slider.value),pattern:selectedPattern},objects:window.csliceViewer?.serializeObjects?.()||[]};}
saveProjectButton?.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(currentProject(),null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${loadedModelName?loadedModelName.replace(/\.stl$/i,""):"CSlice-project"}.cslice.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus("Project saved");});
openProjectButton?.addEventListener("click",()=>projectInput?.click());projectInput?.addEventListener("change",async e=>{const f=e.target.files?.[0];if(f)await loadProject(f);e.target.value="";});
async function loadProject(file){try{const p=JSON.parse(await file.text());if(p.printer&&printerProfiles.some(x=>x.id===p.printer)){printerSelect.value=p.printer;await applyPrinter(printerProfiles.find(x=>x.id===p.printer));}if(p.layerHeight!=null)layerHeightSelect.value=String(p.layerHeight);if(p.infill){slider.value=p.infill.density??20;number.textContent=slider.value;selectedPattern=p.infill.pattern||"Grid";patterns.forEach(x=>x.classList.toggle("selected",x.dataset.pattern===selectedPattern));}for(const o of p.objects||[])if(o.dataUrl){const raw=atob(o.dataUrl.split(",")[1]);const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));window.csliceViewer?.loadSTL(bytes.buffer,o.name,o);}setStatus("Project loaded");}catch(e){console.error(e);setStatus("Could not open this CSlice project");}}
loadPrinterLibrary();loadMaterialLibrary();
