import * as THREE from "three";import{OrbitControls}from"three/addons/controls/OrbitControls.js";import{TransformControls}from"three/addons/controls/TransformControls.js";import{STLLoader}from"three/addons/loaders/STLLoader.js";
const viewport=document.getElementById("viewport"),status=document.getElementById("viewerStatus"),modelInfo=document.getElementById("modelInfo"),overlay=document.getElementById("dropOverlay"),selectionBadge=document.getElementById("selectionBadge");
const scene=new THREE.Scene();scene.background=new THREE.Color(0x0b1120);const camera=new THREE.PerspectiveCamera(45,1,.1,5000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;viewport.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=20;controls.maxDistance=3000;
const transformControls=new TransformControls(camera,renderer.domElement);scene.add(transformControls.getHelper());transformControls.setMode("translate");transformControls.addEventListener("dragging-changed",e=>controls.enabled=!e.value);transformControls.addEventListener("objectChange",()=>{updateSelection();window.csliceApp?.syncObjectList?.()});scene.add(new THREE.HemisphereLight(0xffffff,0x172033,2.1));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(250,400,300);scene.add(key);const fill=new THREE.DirectionalLight(0x8ab4ff,.8);fill.position.set(-300,250,-250);scene.add(fill);
const buildPlate=new THREE.Group();scene.add(buildPlate);const plate=new THREE.Mesh(new THREE.BoxGeometry(1,1,2),new THREE.MeshStandardMaterial({color:0x182235,roughness:.82,metalness:.08}));plate.position.z=-1;buildPlate.add(plate);const grid=new THREE.GridHelper(1,35,0x3b82f6,0x334155);grid.rotation.x=Math.PI/2;grid.position.z=.15;buildPlate.add(grid);const borderGeometry=new THREE.BufferGeometry();buildPlate.add(new THREE.Line(borderGeometry,new THREE.LineBasicMaterial({color:0x60a5fa})));const axes=new THREE.AxesHelper(55);scene.add(axes);
let buildWidth=350,buildDepth=350,buildHeight=350;const objects=new Map();let selectedId=null,nextId=1;const loader=new STLLoader();
function setBuildPlate(w,d,h=350){buildWidth=+w||350;buildDepth=+d||350;buildHeight=+h||350;plate.scale.set(buildWidth,buildDepth,1);grid.scale.set(buildWidth,buildDepth,1);const x=buildWidth/2,y=buildDepth/2;borderGeometry.setFromPoints([new THREE.Vector3(-x,-y,.3),new THREE.Vector3(x,-y,.3),new THREE.Vector3(x,y,.3),new THREE.Vector3(-x,y,.3),new THREE.Vector3(-x,-y,.3)]);axes.position.set(-x+25,-y+25,1);checkAllObjects();fitView();}
function resize(){const w=Math.max(viewport.clientWidth,1),h=Math.max(viewport.clientHeight,1);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}function setStatus(t){status.textContent=t}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function bounds(o){return new THREE.Box3().setFromObject(o)}function size(o){return bounds(o).getSize(new THREE.Vector3())}function fits(o){const b=bounds(o),e=.01;return b.min.x>=-buildWidth/2-e&&b.max.x<=buildWidth/2+e&&b.min.y>=-buildDepth/2-e&&b.max.y<=buildDepth/2+e&&b.min.z>=-e&&b.max.z<=buildHeight+e}function mat(sel){return new THREE.MeshStandardMaterial({color:sel?0x60a5fa:0x4f8fe8,roughness:.58,metalness:.08})}function recolor(o,sel){o.traverse(x=>{if(x.isMesh)x.material.color.set(sel?0x60a5fa:0x4f8fe8)})}
function bufferToDataUrl(buffer){let binary="",bytes=new Uint8Array(buffer);const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));return`data:application/octet-stream;base64,${btoa(binary)}`}
function dataUrlToBuffer(url){const raw=atob(url.split(",")[1]);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out.buffer}
function addSTL(buffer,fileName="model.stl",saved=null){try{const geometry=loader.parse(buffer);geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,mat(false));const id=saved?.id||`object-${nextId++}`;const n=Number(String(id).replace(/\D/g,""));if(n)nextId=Math.max(nextId,n+1);mesh.userData.cslice={id,name:fileName,dataUrl:saved?.dataUrl||bufferToDataUrl(buffer)};const box=bounds(mesh),center=box.getCenter(new THREE.Vector3());mesh.position.x-=center.x;mesh.position.y-=center.y;mesh.position.z-=box.min.z+.0;mesh.position.z+=.8;if(saved){mesh.position.fromArray(saved.position||[0,0,.8]);mesh.rotation.fromArray(saved.rotation||[0,0,0,"XYZ"]);mesh.scale.fromArray(saved.scale||[1,1,1])}scene.add(mesh);objects.set(id,mesh);selectObject(id);overlay.classList.add("hidden");setStatus(`${fileName} loaded`);checkAllObjects();window.csliceApp?.syncObjectList?.();fitSelected();return id}catch(e){console.error(e);setStatus("Could not load that STL file");return null}}
function removeObject(id=selectedId){const o=objects.get(id);if(!o)return;transformControls.detach();scene.remove(o);o.geometry?.dispose();o.material?.dispose();objects.delete(id);selectedId=null;const next=objects.keys().next().value;if(next)selectObject(next);else{selectionBadge.textContent="";modelInfo.innerHTML="<span>No model loaded</span>";setStatus("No objects loaded");overlay.classList.remove("hidden")}window.csliceApp?.syncObjectList?.()}
function duplicateObject(id=selectedId){const src=objects.get(id);if(!src)return;const clone=src.clone();clone.geometry=src.geometry.clone();clone.material=mat(false);const newId=`object-${nextId++}`;clone.userData.cslice={...src.userData.cslice,id:newId,name:src.userData.cslice.name.replace(/\.stl$/i,"")+" copy.stl"};clone.userData.cslice.dataUrl=src.userData.cslice.dataUrl;clone.position.x+=10;clone.position.y+=10;scene.add(clone);objects.set(newId,clone);selectObject(newId);setStatus("Object duplicated")}
function selectObject(id){if(!objects.has(id))return;if(selectedId&&objects.has(selectedId))recolor(objects.get(selectedId),false);selectedId=id;const o=objects.get(id);recolor(o,true);transformControls.attach(o);updateSelection();window.csliceApp?.syncObjectList?.()}
function updateSelection(){if(!selectedId)return;const o=objects.get(selectedId);if(!o)return;const s=size(o),b=bounds(o),ok=fits(o);selectionBadge.textContent=`${o.userData.cslice.name} • ${s.x.toFixed(1)} × ${s.y.toFixed(1)} × ${s.z.toFixed(1)} mm`;modelInfo.innerHTML=`<span><strong>${esc(o.userData.cslice.name)}</strong></span><span>${s.x.toFixed(1)} × ${s.y.toFixed(1)} × ${s.z.toFixed(1)} mm</span><span>${ok?"✓ Fits build volume":"⚠ Outside build volume"}</span><span>Position ${b.min.x.toFixed(1)}, ${b.min.y.toFixed(1)}, ${b.min.z.toFixed(1)} mm</span>`}
function checkAllObjects(){objects.forEach(o=>o.userData.cslice.fits=fits(o));if(selectedId)updateSelection()}
function fitView(){const s=Math.max(buildWidth,buildDepth,buildHeight);camera.position.set(s*.85,s*.85,s);controls.target.set(0,0,0);controls.update()}function fitSelected(){if(!selectedId){fitView();return}const o=objects.get(selectedId);if(!o){fitView();return}const b=bounds(o),c=b.getCenter(new THREE.Vector3()),s=size(o),d=Math.max(s.x,s.y,s.z)*2.2;camera.position.set(c.x+d,c.y+d*.8,c.z+d);controls.target.copy(c);controls.update()}function resetView(){fitView()}function setTransformMode(mode){if(!selectedId){setStatus("Select an object first");return}transformControls.setMode(mode)}
renderer.domElement.addEventListener("pointerdown",e=>{if(e.button!==0||transformControls.dragging)return;const r=renderer.domElement.getBoundingClientRect(),m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,camera);const hits=ray.intersectObjects([...objects.values()],true);if(hits.length){let o=hits[0].object;while(o.parent&&!o.userData.cslice)o=o.parent;if(o.userData.cslice)selectObject(o.userData.cslice.id)}});
window.csliceViewer={loadSTL:addSTL,setBuildPlate,fitModel:fitSelected,fitView,resetView,setTransformMode,selectObject,removeObject,duplicateObject,getSelectedId:()=>selectedId,getObjects:()=>[...objects.entries()].map(([id,o])=>({id,name:o.userData.cslice.name,fits:fits(o),size:size(o).toArray()})),serializeObjects:()=>[...objects.entries()].map(([id,o])=>({id,name:o.userData.cslice.name,dataUrl:o.userData.cslice.dataUrl,position:o.position.toArray(),rotation:o.rotation.toArray(),scale:o.scale.toArray()}))};
window.addEventListener("resize",resize);resize();setBuildPlate(350,350,350);function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();
